export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const START_GAME = 'START_GAME';
export const UPDATE_ACTIVE_CHARACTERS = 'UPDATE_ACTIVE_CHARACTERS';
export const RESTART_VARIABLES = 'RESTART_VARIABLES';
export const SET_PLAYER_ROLS = 'SET_PLAYER_ROLS';
export const UPDATE_PLAYER_INDEX = 'UPDATE_PLAYER_INDEX';